<?php
return [
	'button' => '<button class="ui primary left button" {{attrs}}>{{text}}</button>',
	'checkbox' => '<input type="checkbox" name="{{name}}" value="{{value}}"{{attrs}}>',
	'checkboxFormGroup' => '{{label}}',
	'checkboxWrapper' => '<div class="ui checkbox">{{label}}</div>',
	'dateWidget' => '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}{{meridian}}',
	'error' => '<div class="ui message">{{content}}</div>',
	'errorList' => '<ul class="list">{{content}}</ul>',
	'errorItem' => '<li>{{text}}</li>',
	'file' => '<input type="file" name="{{name}}"{{attrs}}>',
	'fieldset' => '<fieldset{{attrs}}>{{content}}</fieldset>',
	'formStart' => '<form class="ui form"{{attrs}}>',
	'formEnd' => '</form>',
	'formGroup' => '{{label}}{{input}}',
	'hiddenBlock' => '<div style="display:none;">{{content}}</div>',
	'input' => '<input type="{{type}}" name="{{name}}"{{attrs}}/>',
	'inputSubmit' => '<button type="{{type}}"{{attrs}}>{{caption}}</button>',
	'inputContainer' => '<div class="ui labeled input field{{type}}{{required}}">{{content}}{{tooltip}}</div>',
	'inputContainerError' => '<div class="field {{type}}{{required}} error">{{content}}{{error}}</div>',
	'label' => '<label class="ui label"{{attrs}}>{{text}}</label>',
	'nestingLabel' => '{{hidden}}<label{{attrs}}>{{input}}{{text}}</label>',
	'legend' => '<legend>{{text}}</legend>',
	'option' => '<option value="{{value}}"{{attrs}}>{{text}}</option>',
	'optgroup' => '<optgroup label="{{label}}"{{attrs}}>{{content}}</optgroup>',
	'select' => '<select name="{{name}}"{{attrs}}>{{content}}</select>',
	'selectMultiple' => '<select name="{{name}}[]" multiple="multiple"{{attrs}}>{{content}}</select>',
	'radio' => '<input type="radio" name="{{name}}" value="{{value}}"{{attrs}}>',
	'radioWrapper' => '{{label}}',
	'textarea' => '<textarea name="{{name}}"{{attrs}}>{{value}}</textarea>',
	'submitContainer' => '<div class="submit">{{content}}</div>',
];

?>
